name: ci

on:
  push:
    branches:
      - 'master'
  schedule:
   - cron: "0 8 24 * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Install Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v2 
        with:
            registry: ghcr.io
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64
          tags: sunilsankar/postgres-pljava11:latest
